### ISSUE TITLE
./install_openpose_and_enable_package.sh error

### ISSUE THREAD

**Issue by ryo-ponsan** [stevenjj/openpose_ros#18]
Hello.

I couldn't run "install_openpose_and_enable_package.sh".

I Installed openpose and its dependencies,and PCL.
I tried to run the package,but error occurred.

$ ./install_openpose_and_enable_package.sh
Adding CATKIN_IGNORE to this package. Will remove if install script successfully runs
------------------------- Install Script -------------------------
This will run the original install scripts from openpose.
./install_openpose_and_enable_package.sh: line 7: ./install_caffe_and_openpose.sh: No such file or directory
------------------------- Enabling Package -------------------------
Assuming everything in openpose built properly, we remove CATKIN_IGNORE

Could you tell me if I made something wrong or if you could find the way to solve this problem?
(I am new to using Ubuntu)

Let me apologize for my poor English.

**Comment by makino-ryota** [comment]
I found the solution.
I cloned the old openpose package(https://github.com/tramper2/openpose), to the openpose_ros directory.
Then it worked.

I do not know if that is the best, but I solved it.
Thank you.

**Comment by makino-ryota** [comment]
I cloned the old openpose package(https://github.com/tramper2/openpose), to the openpose_ros directory.
Then it worked halfway, but error occurred.
I would be pleased if you have something good solution please let me know.

$ ./install_openpose_and_enable_package.sh
・
・
・
.build_release / tools / extract_features.o: Function `int feature_extraction_pipeline <float> (int, char **) 'within:
`caffe :: Net <float> :: CopyTrainedLayersFrom (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator (std :: allocation_pipelineIfEiiPPc [_Z27feature_extraction_pipelineIfEiiPPc] + 0x1d3): extract_features.cpp: It is an undefined reference to <char>>) '
collect 2: error: ld returned 1 exit status
Makefile: 630: Failed with recipe for target '.build_release / tools / extract_features.bin'
make: *** [.build_release / tools / extract_features.bin] Error 1
make: *** Waiting for incomplete job ....
.build_release / tools / caffe.o: Within function `test () ':
caffe.cpp :(. text + 0x153f): `caffe :: Net <float> :: CopyTrainedLayersFrom (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>>) It is an undefined reference to '
.build_release / tools / caffe.o: Function `CopyLayers (caffe :: Solver <float> *, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &) Inside:
caffe.cpp :(. text + 0x2660): `caffe :: Net <float> :: CopyTrainedLayersFrom (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>>) It is an undefined reference to '
caffe.cpp :(. text + 0x2818): `caffe :: Net <float> :: CopyTrainedLayersFrom (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>>) It is an undefined reference to '
collect 2: error: ld returned 1 exit status
Makefile: 630: Failed with recipe for target '.build_release / tools / caffe.bin'
make: *** [.build_release / tools / caffe.bin] Error 1
.build_release / tools / convert_imageset.o: Within function `main ':
convert_imageset.cpp: (. text.startup + 0xf 52): `caffe :: ReadImageToDatum (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, int, int , undefined reference to int, bool, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, caffe :: Datum *) '
collect 2: error: ld returned 1 exit status
Makefile: 630: Failed with recipe for target '.build_release / tools / convert_imageset.bin'
make: *** [.build_release / tools / convert_imageset.bin] Error 1
.build_release / tools / compute_image_mean.o: Within function `main ':
compute_image_mean.cpp :(. text.startup + 0x333): undefined reference to `caffe :: DecodeDatumNative (caffe :: Datum *) '
compute_image_mean.cpp :(. text.startup + 0x517): undefined reference to `caffe :: DecodeDatumNative (caffe :: Datum *) '
collect 2: error: ld returned 1 exit status
Makefile: 630: Failed with recipe for target '.build_release / tools / compute_image_mean.bin'
make: *** [.build_release / tools / compute_image_mean.bin] Error 1
.build_release / examples / cpp_classification / classification.o: Function `Classifier :: Classifier (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, std :: __ cxx11 std :: allocator <char>> const &, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &, std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>> const &) 'Inside:
classification.cpp :(. text + 0x2cce): `caffe :: Net <float> :: CopyTrainedLayersFrom (std :: __ cxx11 :: basic_string <char, std :: char_traits <char>, std :: allocator <char>>) It is an undefined reference to '
collect 2: error: ld returned 1 exit status
Makefile: 635: Failed with recipe for target '.build_release / examples / cpp_classification / classification.bin'
make: *** [.build_release / examples / cpp_classification / classification.bin] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------
------------------------- Enabling Package ----------------------- -
Assuming everything in openpose built properly, we remove CATKIN_IGNORE

**Comment by ryo-ponsan** [comment]
I will be saved if you tell me which openpose you used.

I tried openpose package which has install_caffe_and_openpose.sh .
(https://github.com/tramper2/openpose.git) and (https://github.com/clcarwin/openpose_body_hand_face_landmark.git)
 But, it error occured.

**Comment by stevenjj** [comment]
Hi Ryo,

In the main github page for the project (https://github.com/stevenjj/openpose_ros) I have a link to which openpose version we used for this project. The version is specified by the commit number.

Here is the link to that openpose version for your convenience: 
https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/a1e0a5f4136e702b5731a268c2993fb75ca4753c

Please try that version and let me know if you come across other problems.

**Comment by ryo-ponsan** [comment]
Thank you for replying.
I am sorry for replying late.
I missed about openpose's version on github...Thank you for teaching me.

But it error occured...


I tried to use this(https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/a1e0a5f4136e702b5731a268c2993fb75ca4753c),but it error occured like this.


-----------------

CXX/LD -o .build_release/examples/cpp_classification/classification.bin
.build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x1d3): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1
make: *** Waiting for unfinished jobs....
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0xf52): undefined reference to `caffe::ReadImageToDatum(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Datum*)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1
.build_release/tools/caffe.o: In function `test()':
caffe.cpp:(.text+0x153f): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
.build_release/tools/caffe.o: In function `CopyLayers(caffe::Solver<float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
caffe.cpp:(.text+0x2660): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
caffe.cpp:(.text+0x2818): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1
.build_release/tools/compute_image_mean.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x333): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
compute_image_mean.cpp:(.text.startup+0x517): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
.build_release/examples/cpp_classification/classification.o: In function `Classifier::Classifier(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
classification.cpp:(.text+0x331e): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
.build_release/examples/cpp_classification/classification.o: In function `main':
classification.cpp:(.text.startup+0x23d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
Makefile:635: recipe for target '.build_release/examples/cpp_classification/classification.bin' failed
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------
------------------------- Enabling Package -------------------------
Assuming everything in openpose built properly, we remove CATKIN_IGNORE



I am searching about this solution now, but I am pleased to tell you if you have any advice.

add information

my pc environment is this.
CPU : Intel Core i9-8950HK 2.9GHz  
RAM :32GB DDR4
Graphics : NVIDIA GeForce GTX 1080
OS : Ubuntu 16.04 LTS
OpenCV3.2.0

**Comment by stevenjj** [comment]
Hello, at this point of the install script (which we did not write), it is still trying to build the old openpose version. The errors show some missing system dependencies.

It looks like you don't have caffe installed  ( http://caffe.berkeleyvision.org/install_apt.html )  and some functions of openCV are not being found. It's likely that caffe and openCV are just not installed properly in your system.

**Comment by ryo-ponsan** [comment]
Thank you.
Now, I am struggling now, but I am trying to install it.
I will contact you as soon as I have progress.

**Comment by makino-ryota** [comment]
I have questions.

①Is my way is right?↓
I cloned "openpose_ros-master" and cloned "openpose(https://github.com/CMU-Perceptual-Computing-Lab/openpose/tree/a1e0a5f4136e702b5731a268c2993fb75ca4753c)" under "openpose_ros-master" directory. Both of them are installed by zip file and unzipped.
And...
I consider that I can install openpose and caffe by running under "openpose_ros-master/openpose" directory's file, which name is "install_caffe_and_openpose.sh."
Is this right?

②And...many errors are occurred for "protobuf".
So, I would like to know, what is your version of protobuf?

Sorry for the long question.

**Comment by makino-ryota** [comment]
2days ago, I didnt install Caffe, so I tried to install by "install_caffe_and_openpose.sh" which directory is /openpose_ros-master/openpose/ .

Then error occurred with protobuf. So I Installed protobuf (https://github.com/protocolbuffers/protobuf) in /openpose_ros-master/openpose/ 3rdparty and installed it.
But error occurred.
I think it's due to protobuf's version...

Please let me know the version of ”protobuf” you are using if you do not mind.
Or If my awareness is wrong, I would appreciate it if you tell me.

------------------------- Compiling Caffe -------------------------
CXX/LD -o .build_release/tools/convert_imageset.bin
CXX/LD -o .build_release/tools/compute_image_mean.bin
CXX/LD -o .build_release/tools/extract_features.bin
CXX/LD -o .build_release/tools/caffe.bin
CXX/LD -o .build_release/examples/cpp_classification/classification.bin
/usr/bin/ld: warning: libprotobuf.so.9, needed by /usr/local/lib/libcaffe.so, may conflict with libprotobuf.so.17
.build_release/tools/compute_image_mean.o: In function `main':
compute_image_mean.cpp:(.text.startup+0x333): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
compute_image_mean.cpp:(.text.startup+0x4b6): undefined reference to `caffe::DecodeDatumNative(caffe::Datum*)'
/usr/bin/ld: warning: libprotobuf.so.9, needed by /usr/local/lib/libcaffe.so, may conflict with libprotobuf.so.17
.build_release/tools/convert_imageset.o: In function `main':
convert_imageset.cpp:(.text.startup+0xf52): undefined reference to `caffe::ReadImageToDatum(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int, int, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, caffe::Datum*)'
/usr/bin/ld: warning: libprotobuf.so.9, needed by /usr/local/lib/libcaffe.so, may conflict with libprotobuf.so.17
.build_release/tools/caffe.o: In function `test()':
caffe.cpp:(.text+0x153f): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
.build_release/tools/caffe.o: In function `CopyLayers(caffe::Solver<float>*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
caffe.cpp:(.text+0x26f0): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
caffe.cpp:(.text+0x28a8): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
.build_release/tools/caffe.o: In function `train()':
caffe.cpp:(.text+0x2cd1): undefined reference to `caffe::NetState* google::protobuf::Arena::CreateMaybeMessage<caffe::NetState>(google::protobuf::Arena*)'
caffe.cpp:(.text+0x406c): undefined reference to `caffe::NetState* google::protobuf::Arena::CreateMaybeMessage<caffe::NetState>(google::protobuf::Arena*)'
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/convert_imageset.bin' failed
make: *** [.build_release/tools/convert_imageset.bin] Error 1
make: *** Waiting for unfinished jobs....
Makefile:630: recipe for target '.build_release/tools/compute_image_mean.bin' failed
make: *** [.build_release/tools/compute_image_mean.bin] Error 1
Makefile:630: recipe for target '.build_release/tools/caffe.bin' failed
make: *** [.build_release/tools/caffe.bin] Error 1
/usr/bin/ld: warning: libprotobuf.so.9, needed by /usr/local/lib/libcaffe.so, may conflict with libprotobuf.so.17
.build_release/tools/extract_features.o: In function `int feature_extraction_pipeline<float>(int, char**)':
extract_features.cpp:(.text._Z27feature_extraction_pipelineIfEiiPPc[_Z27feature_extraction_pipelineIfEiiPPc]+0x1d3): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
collect2: error: ld returned 1 exit status
Makefile:630: recipe for target '.build_release/tools/extract_features.bin' failed
make: *** [.build_release/tools/extract_features.bin] Error 1
/usr/bin/ld: warning: libprotobuf.so.9, needed by /usr/local/lib/libcaffe.so, may conflict with libprotobuf.so.17
.build_release/examples/cpp_classification/classification.o: In function `Classifier::Classifier(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
classification.cpp:(.text+0x331e): undefined reference to `caffe::Net<float>::CopyTrainedLayersFrom(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
.build_release/examples/cpp_classification/classification.o: In function `main':
classification.cpp:(.text.startup+0x23d): undefined reference to `cv::imread(cv::String const&, int)'
collect2: error: ld returned 1 exit status
Makefile:635: recipe for target '.build_release/examples/cpp_classification/classification.bin' failed
make: *** [.build_release/examples/cpp_classification/classification.bin] Error 1

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.
------------------------- -------------------------

------------------------- -------------------------
Errors detected. Exiting script. The software might have not been successfully installed.

**Comment by ryo-ponsan** [comment]
According to this page, I can install it!!(https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/a1e0a5f4136e702b5731a268c2993fb75ca4753c/doc/installation.md)
I did not understand basic things.
Thank you so much.

And, I have a question, can I use openpose_ros on ROS kinetic instead of ROS indigo?
It has nothing to do with the title but I am glad if you tell me.

**Comment by stevenjj** [comment]
I'm glad you were able to install openpose.
The 2D wrapper uses basic ROS functions, so it should be ok.

The 3D algorithm itself is in C++ with the kinetic version of `pcl_ros`. I believe it should be ok. 

Looks like installing openpose on its own is resolved, so we can close this issue now. Feel free to open a new issue regarding using the package itself.
